print('Hello world')
print('What is your name?')
myName = input()
print ('It is good to meet you,'+ myName)
print('The lenght of you name is:')
print(len(myName))
print('What is your age?')
myage = input()
print('you will be '+str(int(myage)+1)+' in a year')